version: '3'

services:
  database:
    image: "postgres"
    env_file:
      - database.env
    ports:
      - "5433:5432"
    volumes:
      - database-data:/var/lib/postgresql/data/

volumes:
  database-data:
